/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Dialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Veroko
 */
public class kiosco_menu_principal extends javax.swing.JFrame {

    /**
     * Creates new form kiosco_menu_principal
     */
    public kiosco_menu_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpn_kiosco_menu_principal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_kiosco_menu_principal_venta = new javax.swing.JButton();
        btn_kiosco_menu_principal_opciones = new javax.swing.JButton();
        btn_kiosco_menu_principal_salir = new javax.swing.JButton();
        btn_kiosco_menu_principal_productos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("jFrameMenu"); // NOI18N

        jpn_kiosco_menu_principal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¡Bienvenido!");

        btn_kiosco_menu_principal_venta.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btn_kiosco_menu_principal_venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icon/cereal.png"))); // NOI18N
        btn_kiosco_menu_principal_venta.setText("Venta");
        btn_kiosco_menu_principal_venta.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_kiosco_menu_principal_venta.setIconTextGap(10);
        btn_kiosco_menu_principal_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kiosco_menu_principal_ventaActionPerformed(evt);
            }
        });

        btn_kiosco_menu_principal_opciones.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btn_kiosco_menu_principal_opciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icon/instrumentos.png"))); // NOI18N
        btn_kiosco_menu_principal_opciones.setText("Opciones");
        btn_kiosco_menu_principal_opciones.setIconTextGap(10);
        btn_kiosco_menu_principal_opciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kiosco_menu_principal_opcionesActionPerformed(evt);
            }
        });

        btn_kiosco_menu_principal_salir.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btn_kiosco_menu_principal_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icon/cerrar.png"))); // NOI18N
        btn_kiosco_menu_principal_salir.setText("Salir");
        btn_kiosco_menu_principal_salir.setIconTextGap(10);
        btn_kiosco_menu_principal_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kiosco_menu_principal_salirActionPerformed(evt);
            }
        });

        btn_kiosco_menu_principal_productos.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btn_kiosco_menu_principal_productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icon/panadero.png"))); // NOI18N
        btn_kiosco_menu_principal_productos.setText("Productos");
        btn_kiosco_menu_principal_productos.setIconTextGap(10);
        btn_kiosco_menu_principal_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kiosco_menu_principal_productosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpn_kiosco_menu_principalLayout = new javax.swing.GroupLayout(jpn_kiosco_menu_principal);
        jpn_kiosco_menu_principal.setLayout(jpn_kiosco_menu_principalLayout);
        jpn_kiosco_menu_principalLayout.setHorizontalGroup(
            jpn_kiosco_menu_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_kiosco_menu_principalLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jpn_kiosco_menu_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpn_kiosco_menu_principalLayout.createSequentialGroup()
                        .addComponent(btn_kiosco_menu_principal_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_kiosco_menu_principal_productos, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpn_kiosco_menu_principalLayout.createSequentialGroup()
                        .addComponent(btn_kiosco_menu_principal_opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_kiosco_menu_principal_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jpn_kiosco_menu_principalLayout.setVerticalGroup(
            jpn_kiosco_menu_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_kiosco_menu_principalLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jpn_kiosco_menu_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_kiosco_menu_principal_venta, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(btn_kiosco_menu_principal_productos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addGroup(jpn_kiosco_menu_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_kiosco_menu_principal_opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_kiosco_menu_principal_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpn_kiosco_menu_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpn_kiosco_menu_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kiosco_menu_principal_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kiosco_menu_principal_salirActionPerformed
        this.setVisible(false);
        kiosco_inicio jframeKiosco = new kiosco_inicio();
        
        jframeKiosco.setVisible(true);
        
    }//GEN-LAST:event_btn_kiosco_menu_principal_salirActionPerformed

    private void btn_kiosco_menu_principal_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kiosco_menu_principal_ventaActionPerformed
        this.setVisible(false);
        kiosco_venta jframeVenta = new kiosco_venta();
        
        jframeVenta.setVisible(true);
    }//GEN-LAST:event_btn_kiosco_menu_principal_ventaActionPerformed

    private void btn_kiosco_menu_principal_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kiosco_menu_principal_productosActionPerformed
        this.setVisible(false);
        kiosco_productos jframeProductos = new kiosco_productos();
        
        jframeProductos.setVisible(true);
    }//GEN-LAST:event_btn_kiosco_menu_principal_productosActionPerformed

    private void btn_kiosco_menu_principal_opcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kiosco_menu_principal_opcionesActionPerformed
        this.setVisible(false);
        kiosco_opciones jframeOpciones = new kiosco_opciones();
        
        jframeOpciones.setVisible(true);
    }//GEN-LAST:event_btn_kiosco_menu_principal_opcionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kiosco_menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kiosco_menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kiosco_menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kiosco_menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kiosco_menu_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kiosco_menu_principal_opciones;
    private javax.swing.JButton btn_kiosco_menu_principal_productos;
    private javax.swing.JButton btn_kiosco_menu_principal_salir;
    private javax.swing.JButton btn_kiosco_menu_principal_venta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jpn_kiosco_menu_principal;
    // End of variables declaration//GEN-END:variables
}
