/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controller.Data;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Veroko
 */
public class kiosco_opciones extends javax.swing.JFrame {

    private Data d;

    public kiosco_opciones() {
        try {
            d = new Data();
            initComponents();
            init();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(kiosco_opciones.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(kiosco_opciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpn_kiosco_opciones = new javax.swing.JPanel();
        btn_kiosco_opciones_cambiar_clave = new javax.swing.JButton();
        jpn_cambiar_clave = new javax.swing.JPanel();
        jpass_cambiar_clave_actual = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jpass_cambiar_clave_nueva = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jpass_cambiar_clave_confirmar = new javax.swing.JPasswordField();
        btn_cambiar_clave_confirmar = new javax.swing.JButton();
        btn_cambiar_clave_cancelar = new javax.swing.JButton();
        btn_kiosco_opciones_volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpn_kiosco_opciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_kiosco_opciones_cambiar_clave.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_kiosco_opciones_cambiar_clave.setText("Cambiar contraseña");
        btn_kiosco_opciones_cambiar_clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kiosco_opciones_cambiar_claveActionPerformed(evt);
            }
        });

        jpn_cambiar_clave.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jpass_cambiar_clave_actual.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Ingrese contraseña actual: ");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Ingrese nueva contraseña: ");

        jpass_cambiar_clave_nueva.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Confirme contraseña: ");

        jpass_cambiar_clave_confirmar.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btn_cambiar_clave_confirmar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_cambiar_clave_confirmar.setText("Confirmar");
        btn_cambiar_clave_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cambiar_clave_confirmarActionPerformed(evt);
            }
        });

        btn_cambiar_clave_cancelar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_cambiar_clave_cancelar.setText("Cancelar");
        btn_cambiar_clave_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cambiar_clave_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpn_cambiar_claveLayout = new javax.swing.GroupLayout(jpn_cambiar_clave);
        jpn_cambiar_clave.setLayout(jpn_cambiar_claveLayout);
        jpn_cambiar_claveLayout.setHorizontalGroup(
            jpn_cambiar_claveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_cambiar_claveLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(jpn_cambiar_claveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpn_cambiar_claveLayout.createSequentialGroup()
                        .addComponent(btn_cambiar_clave_confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cambiar_clave_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpn_cambiar_claveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jpass_cambiar_clave_nueva, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jpass_cambiar_clave_actual, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jpass_cambiar_clave_confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jpn_cambiar_claveLayout.setVerticalGroup(
            jpn_cambiar_claveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_cambiar_claveLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpass_cambiar_clave_actual, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpass_cambiar_clave_nueva, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpass_cambiar_clave_confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jpn_cambiar_claveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cambiar_clave_confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cambiar_clave_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        btn_kiosco_opciones_volver.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_kiosco_opciones_volver.setText("Volver");
        btn_kiosco_opciones_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kiosco_opciones_volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpn_kiosco_opcionesLayout = new javax.swing.GroupLayout(jpn_kiosco_opciones);
        jpn_kiosco_opciones.setLayout(jpn_kiosco_opcionesLayout);
        jpn_kiosco_opcionesLayout.setHorizontalGroup(
            jpn_kiosco_opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_kiosco_opcionesLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jpn_kiosco_opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_kiosco_opciones_cambiar_clave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_kiosco_opciones_volver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addComponent(jpn_cambiar_clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jpn_kiosco_opcionesLayout.setVerticalGroup(
            jpn_kiosco_opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpn_kiosco_opcionesLayout.createSequentialGroup()
                .addGroup(jpn_kiosco_opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpn_kiosco_opcionesLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jpn_cambiar_clave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpn_kiosco_opcionesLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(btn_kiosco_opciones_cambiar_clave, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btn_kiosco_opciones_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpn_kiosco_opciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpn_kiosco_opciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kiosco_opciones_cambiar_claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kiosco_opciones_cambiar_claveActionPerformed
        jpn_cambiar_clave.setVisible(true);
        btn_kiosco_opciones_cambiar_clave.setEnabled(false);
    }//GEN-LAST:event_btn_kiosco_opciones_cambiar_claveActionPerformed

    private void btn_cambiar_clave_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cambiar_clave_cancelarActionPerformed
        jpn_cambiar_clave.setVisible(false);
        btn_kiosco_opciones_cambiar_clave.setEnabled(true);
        clear();
    }//GEN-LAST:event_btn_cambiar_clave_cancelarActionPerformed

    private void btn_kiosco_opciones_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kiosco_opciones_volverActionPerformed
        this.setVisible(false);
        kiosco_menu_principal jframeMenu = new kiosco_menu_principal();
        jframeMenu.setVisible(true);
        clear();
    }//GEN-LAST:event_btn_kiosco_opciones_volverActionPerformed

    private void btn_cambiar_clave_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cambiar_clave_confirmarActionPerformed

        try {
            String passActual = new String(jpass_cambiar_clave_actual.getPassword());
            String newPass = new String(jpass_cambiar_clave_nueva.getPassword());
            String confirmPass = new String(jpass_cambiar_clave_confirmar.getPassword());

            if ((!passActual.equals(d.buscarPassword(passActual))) || (passActual.equals(""))) {
                JOptionPane.showMessageDialog(null, "Contraseña actual no valida", "ERROR", JOptionPane.OK_OPTION);
            } else {
                if ((!newPass.equals(confirmPass)) || (newPass.equals("")) || (confirmPass.equals(""))) {
                    JOptionPane.showMessageDialog(null, "Nuevas contraseñas no coinciden", "ERROR", JOptionPane.OK_OPTION);
                } else {
                    d.actualizarPassword(newPass);
                    JOptionPane.showMessageDialog(null, "Contraseña cambiada. Vuelva a iniciar se sesión con su nueva contraseña");
                }
            }
            clear();

            this.setVisible(false);
            kiosco_inicio jframeKiosco = new kiosco_inicio();

            jframeKiosco.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(kiosco_opciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_cambiar_clave_confirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kiosco_opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kiosco_opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kiosco_opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kiosco_opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kiosco_opciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cambiar_clave_cancelar;
    private javax.swing.JButton btn_cambiar_clave_confirmar;
    private javax.swing.JButton btn_kiosco_opciones_cambiar_clave;
    private javax.swing.JButton btn_kiosco_opciones_volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jpass_cambiar_clave_actual;
    private javax.swing.JPasswordField jpass_cambiar_clave_confirmar;
    private javax.swing.JPasswordField jpass_cambiar_clave_nueva;
    private javax.swing.JPanel jpn_cambiar_clave;
    private javax.swing.JPanel jpn_kiosco_opciones;
    // End of variables declaration//GEN-END:variables

    private void clear() {
        jpass_cambiar_clave_actual.setText(null);
        jpass_cambiar_clave_nueva.setText(null);
        jpass_cambiar_clave_confirmar.setText(null);
    }

    ;
    
    private void init() {

        jpn_cambiar_clave.setVisible(false);

    }
}
